language: python
sudo: false
cache: pip

python:
  - "2.7"

addons:
  postgresql: "9.6"
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml # because pip installation is slow
      - postgis postgresql-9.6-postgis-2.3 # travis doesn't know which one to install
      - postgresql-9.6-postgis-2.3-scripts # pre-installed on travis but required for runbot

virtualenv:
  system_site_packages: true

env:
  global:
    - VERSION="10.0" TESTS="0" LINT_CHECK="0" MAKEPOT="0"

  matrix:
  - LINT_CHECK="1"
  - TESTS="1" ODOO_REPO="odoo/odoo" LINT_CHECK="0" MAKEPOT="1"
  - TESTS="1" ODOO_REPO="OCA/OCB" LINT_CHECK="0"

install:
  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  - pip install geojson Shapely sphinx sphinx_bootstrap_theme sphinx-intl odoo-sphinx-autodoc responses

before_script:
  - psql -U postgres -d postgres -c "create extension postgis"
  - psql -U postgres -d postgres -c "create extension postgis_topology"

script:
  - if [ -z "$DOCS" ] ; then travis_run_tests; fi
  - if [ -n "$DOCS" ] ; then ./.travis_build_doc; fi

after_success:
  - if [ -z "$DOCS" ] ; then travis_after_tests_success; fi
  - if [ -n "$DOCS" ] ; then ./.travis_push_doc; fi
